language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    env: TOXENV=WIN
    sudo: false
  - os: linux
    dist: trusty
    sudo: false
  - os: osx
    osx_image: xcode8
addons:
  apt:
    packages:
    - g++-mingw-w64
    - cmake3
before_script:
- export PATH="$HOME/bin:$PATH"
- make -f texinfo-travis.mk install_texinfo
script:
- export REV=dirty-$(git describe --always)
- git clone https://github.com/vitasdk/buildscripts.git
# this fixes an issue with including .h files from c++
# https://github.com/vitasdk/buildscripts/pull/51
# and an issue with templates, static functions and lambdas
# https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85646
# and an issue with linking of exidx tables and their relocations
# https://sourceware.org/bugzilla/show_bug.cgi?id=23839
- patch --directory buildscripts -p1 < buildscripts.patch
- chmod +x *.sh
- "./build.sh"
before_deploy:
- ". ./before_deploy.sh"
deploy:
  provider: releases
  api_key:
    secure: cuqggNP2YIfL/a+V4Hl+VUwXKWYrRxaJAnWhNsTh7z/kduZzwYLkqIrUQggZFPrirJqzUjXMlLJ0tsHYFVbmRqcCv/Zc2rp86vSaku+fLcmaHeKndiQUogjxY7MdGpvZhbCY6bao1yHrq31Qlmj3FRr56A/TIZEOuz9lsNFcyQGsqgruznTND1LJdKUfA2lFtsUlkSLnidWJ/TCua8kqnToybXnQqjt6pV4p3SntxxKPEcSux+2nkQidUkvspt6Oxv45S6hPRnwRvJyumuMCAL+8d+MRU/quQ5eCH2j1kjzPd2iVBbD1VcOXQoTPwjPO8pNYcnFk/z+RJ8Q3kGbDC4gdOWi8ktPJ7InKLlRUoPf/Cq4A9uPvnVo+TiRVwY41hE6YtF0SEMelSm7jdcsStPqq9p4bE/hM2NcXhi9fa+SQQG8UJ/iVX8zPngL1vfF6iB51n2bsT3zprkkomykGcCWcLPGtNMFxam9nWA0r8fAJzv9+zxXfgtf/OpbHipeObLqRuZQy6eG4cpCToycb7l6hgu0SFzLMUKJ3W8eu1Ky3bEQcbZ4/yOonnWvIatmYWlT1b+nvwD9tRN8w+HOCgMoHmqNmUF34pHeVj0BTVsnNUAV6PRRMLEPHMjqX5N7cLyMtUgffRpPsJCIevWn8cghqPgj6dINvGmoeUQTWbVg=
  file_glob: true
  file: buildscripts/build/*.tar.bz2
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
    repo: blastrock/autobuilds
branches:
  except:
  - "/^*-v[0-9]/"
env:
  global:
    secure: "ZQ9J1F3HLZrgYJVvQRcLRkGG3Zv3vnjHAAM7jKXDez5rtZOigGoc7vkYZ7QVeAIeBCE3XxYloII2Y5gohIU6n3tG5NRikNBfNkvndBeG9pYZd9fBl2xgrkJ29F3mFqDY8yhGWFsd59d3VBPAkrpW+Q715wcgqt9Aun21N1gZAR3cR7rCwIF9OFgR3uTCVl8wPUmDWZS8SDXTKTSOigOtJm/xswiu9OqhMBxsty+IPlJhY1RxiCiIze11t0XSJN6ojXJy6mpZe+IXczTNVDrDZqhf3rXs6f140nKa9xkz/nJvAuOYOxGQGxf1+NwCbA9ZCrCY5gkeg4omIZTjHMclJQr3n0+0913zSd7ucDVjGR5AEUhJb2KZJes+lVyJVid1YrKVqdTYDdOwXGxz+o1nTYponTZ2Orb4ASjmfJf3nCP6Kp6tlcNHPN5Exzlw6C9pUL6qp/6Ho8/fSCOZOru6vTORr3ygICZ071JHK/Fm9uFhDDwDZV+ZLDNzXvIV4uJOYdh4bdOP2R2eTnX81DDPfBnonHG3X8q2eb63ysJT7gTQR0Ko66KDntzzq7vIY/AcG5D4KeJqJXLtaQigZ+gt6VTn0THU04lK1SlSUNs3oxuCwjL2UfoCn9MmWa91Hmobh0x7Bn2LScAaSlkJIMGPimVy9NVqeVko6iVPhjkdKEU="
